name: matrix4_transform
description: A helper math class for easily creating Matrix4 transformations, which you can use in the Container's transform parameter and elsewhere.
version: 4.0.1
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/matrix4_transform
topics:
  - math
  - animation
  - image-transformations

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
