name: matrix4_transform
description: Helper math class for easily creating Matrix4 transformations, that you can use in Container's transform parameter and elsewhere.
version: 3.0.0
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/matrix4_transform

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
